FROM hyperledger/fabric-baseos:_BASE_TAG_
ENV FABRIC_CA_HOME /etc/hyperledger/fabric-ca
RUN mkdir -p $FABRIC_CA_HOME /var/hyperledger/fabric-ca
COPY payload/fabric-ca /usr/local/bin

# Copy the configuration files
ADD payload/sampleconfig.tar.bz2 $FABRIC_CA_HOME

EXPOSE 7054
CMD fabric-ca server start -address 0.0.0.0 -ca $FABRIC_CA_HOME/ec.pem -ca-key $FABRIC_CA_HOME/ec-key.pem -config $FABRIC_CA_HOME/server-config.json
